#!/usr/bin/env python3
# merge_vcf_app 1.0.0
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# See https://documentation.dnanexus.com/developer for documentation and
# tutorials on how to modify this file.
#
# DNAnexus Python Bindings (dxpy) documentation:
# http://autodoc.dnanexus.com/bindings/python/current/
import os
import subprocess
import dxpy
import gzip
from concurrent.futures import ThreadPoolExecutor

def find_bcftools_path():
    try:
        bcftools_path = subprocess.check_output(['which', 'bcftools']).strip()
        return bcftools_path.decode('utf-8')
    except subprocess.CalledProcessError:
        return None

def find_bgzip_path():
    try:
        bgzip_path = subprocess.check_output(['which', 'bgzip']).strip()
        return bgzip_path.decode('utf-8')
    except subprocess.CalledProcessError:
        return None

def check_bcftools_installed():
    return find_bcftools_path() is not None

def check_bgzip_installed():
    return find_bgzip_path() is not None

def install_bcftools():
    try:
        subprocess.run(['apt-get', 'update'], check=True)
        subprocess.run(['apt-get', 'install', '-y', 'bcftools'], check=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error: Failed to install bcftools. Exit code: {e.returncode}")
        return False

def install_tabix():
    try:
        subprocess.run(['apt-get', 'update'], check=True)
        subprocess.run(['apt-get', 'install', '-y', 'tabix'], check=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error: Failed to install tabix. Exit code: {e.returncode}")
        return False

def check_vcf_headers(vcf_file, bcftools_path):
    try:
        subprocess.run([bcftools_path, 'view', '--no-version', vcf_file], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        print(f"Checked VCF file headers: {vcf_file}")
    except subprocess.CalledProcessError as e:
        print(f"Error: BCFtools view command failed with exit code {e.returncode}")


def detect_chromosome_prefix(vcf_file):
    open_func = gzip.open if vcf_file.endswith('.gz') else open
    with open_func(vcf_file, 'rt') as fin:
        for line in fin:
            if line.startswith('#'):
                continue
            columns = line.strip().split('\t')
            if not columns:
                continue
            chromosome = columns[0].lower()
            if chromosome.startswith('chr'):
                return 'chr'
            return ''
    return 'chr'


def region_has_variants(vcf_file, region, bcftools_path):
    process = subprocess.Popen(
        [bcftools_path, 'view', '-H', '--regions', region, vcf_file],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    try:
        return bool(process.stdout.readline())
    finally:
        if process.stdout is not None:
            process.stdout.close()
        try:
            process.kill()
        except OSError:
            pass
        process.wait()


def remove_format_variables(vcf_file, bcftools_path):

    open_func = gzip.open if vcf_file.endswith('.gz') else open
    with open_func(vcf_file, 'rt') as fin:
        for line in fin:
            if line.startswith('#CHROM'):
                columns = line.strip().split('\t')
                if len(columns) > 8 and columns[8] == 'GT':
                    print(f"{vcf_file} already only has GT FORMAT. Skipping annotate.")
                    return vcf_file
                break

    cleaned_vcf = f"cleaned_{os.path.basename(vcf_file)}"
    try:
        subprocess.run([
            bcftools_path, 'annotate',
            '-x', 'FORMAT,^GT',
            vcf_file, '-Oz', '-o', cleaned_vcf
        ], check=True)
        print(f"Cleaned VCF file saved as: {cleaned_vcf}")
        return cleaned_vcf
    except subprocess.CalledProcessError as e:
        print(f"Error: BCFtools annotate command failed with exit code {e.returncode}")
        return None



def index_vcf_file(vcf_file, bcftools_path):
    try:
        subprocess.run([bcftools_path, 'index', vcf_file], check=True)
        print(f"Indexed VCF file: {vcf_file}")
    except subprocess.CalledProcessError as e:
        print(f"Error: BCFtools index command failed with exit code {e.returncode}")

def normalize_and_split_vcf(input_vcf, output_vcf, reference_genome, bcftools_path):
    try:
        subprocess.run([bcftools_path, 'norm', '-m', '-any', '-f', reference_genome, '-o', output_vcf, input_vcf], check=True)
        print(f"Normalized and split VCF file saved as: {output_vcf}")
    except subprocess.CalledProcessError as e:
        print(f"Error: BCFtools norm command failed with exit code {e.returncode}")

def compress_vcf_with_bgzip(vcf_file, bgzip_path):
    try:
        subprocess.run([bgzip_path, vcf_file], check=True)
        print(f"Compressed VCF file with bgzip: {vcf_file}.gz")
    except subprocess.CalledProcessError as e:
        print(f"Error: bgzip command failed with exit code {e.returncode}")

def merge_vcf_files(input_vcf_files, output_vcf, bcftools_path):
    try:
        subprocess.run([bcftools_path, 'merge', '-O', 'z', '-o', output_vcf] + input_vcf_files, check=True)
        print(f"Merged VCF file saved as: {output_vcf}")
    except subprocess.CalledProcessError as e:
        print(f"Error: BCFtools merge command failed with exit code {e.returncode}")

def split_vcf_by_chromosome(merged_vcf, bcftools_path):
    chromosome_prefix = detect_chromosome_prefix(merged_vcf)
    if chromosome_prefix:
        print(f"Detected chromosome naming style with 'chr' prefix in {merged_vcf}")
    else:
        print(f"Detected chromosome naming style without 'chr' prefix in {merged_vcf}")

    chromosomes = [str(i) for i in range(1, 23)] + ['X', 'Y']
    split_vcf_files = []
    for chromosome in chromosomes:
        region_name = f"{chromosome_prefix}{chromosome}"
        output_chr_vcf = f"merged_chr{chromosome}.vcf.gz"

        if not region_has_variants(merged_vcf, region_name, bcftools_path):
            print(f"No variants found for {region_name}; skipping {output_chr_vcf}")
            continue

        try:
            subprocess.run([bcftools_path, 'view', '-Oz', merged_vcf, '--regions', region_name, '-o', output_chr_vcf], check=True)
            index_vcf_file(output_chr_vcf, bcftools_path)
            print(f"Split VCF file saved as: {output_chr_vcf}")
            split_vcf_files.append(output_chr_vcf)
        except subprocess.CalledProcessError as e:
            print(f"Error: BCFtools view command failed for {region_name} with exit code {e.returncode}")
            return None
    return split_vcf_files

def ensure_bgzipped(vcf_file, bgzip_path):
    if vcf_file.endswith('.vcf.gz'):
        return vcf_file
    gzipped_vcf = vcf_file + '.gz'
    subprocess.run([bgzip_path, vcf_file], check=True)
    print(f"Compressed {vcf_file} to {gzipped_vcf}")
    return gzipped_vcf

@dxpy.entry_point('main')
def main(input_vcfs, reference_genome, **kwargs):
    index_files = kwargs.get('index_files', None)
    
    input_vcf_files = []
    for i, file in enumerate(input_vcfs):
        file_id = file['$dnanexus_link'] if isinstance(file, dict) else file
        # Download with original filename
        orig_name = file.get('name') if isinstance(file, dict) and 'name' in file else None
        if orig_name:
            local_filename = f"input_{i}_" + orig_name
        else:
            local_filename = f"input_{i}.vcf"
        subprocess.run(['dx', 'download', file_id, '-o', local_filename], check=True)
        input_vcf_files.append(local_filename)
    
    reference_genome_file = reference_genome['$dnanexus_link'] if isinstance(reference_genome, dict) else reference_genome
    local_reference_genome = "reference_genome.fa"
    subprocess.run(['dx', 'download', reference_genome_file, '-o', local_reference_genome], check=True)
    
    bcftools_path = find_bcftools_path()
    if not bcftools_path:
        print("BCFtools is not installed. Installing...")
        if not install_bcftools():
            print("Installation of BCFtools failed. Exiting.")
            return
        bcftools_path = find_bcftools_path()
    
    bgzip_path = find_bgzip_path()
    if not bgzip_path:
        print("bgzip is not installed. Installing tabix...")
        if not install_tabix():
            print("Installation of tabix failed. Exiting.")
            return
        bgzip_path = find_bgzip_path()

    if bgzip_path is None:
        raise RuntimeError("bgzip executable not found after installation.")

    # Ensure all input VCFs are bgzipped before indexing
    input_vcf_files = [ensure_bgzipped(vcf, bgzip_path) for vcf in input_vcf_files]

    
    if index_files:
        print("Optional index files detected. Using provided index files.")
        for i, file in enumerate(index_files):
            file_id = file['$dnanexus_link'] if isinstance(file, dict) else file
            local_filename = f"input_{i}.vcf.gz.tbi"
            subprocess.run(['dx', 'download', file_id, '-o', local_filename], check=True)
    else:
        print("No optional index files detected. Indexing VCF files on the worker.")
        with ThreadPoolExecutor() as executor:
            executor.map(lambda vcf_file: index_vcf_file(vcf_file, bcftools_path), input_vcf_files)
    
    # Check and fix VCF headers
    with ThreadPoolExecutor() as executor:
        executor.map(lambda vcf_file: check_vcf_headers(vcf_file, bcftools_path), input_vcf_files)
    
    # Remove other FORMAT variables but only keep GT
    with ThreadPoolExecutor() as executor:
        cleaned_vcf_files = list(executor.map(lambda vcf_file: remove_format_variables(vcf_file, bcftools_path), input_vcf_files))
        
    # Index the cleaned VCF files
    with ThreadPoolExecutor() as executor:
        executor.map(lambda vcf_file: index_vcf_file(vcf_file, bcftools_path), cleaned_vcf_files)
    
    # Merge VCF files
    merged_vcf = "merged_output.vcf.gz"
    merge_vcf_files(cleaned_vcf_files, merged_vcf, bcftools_path)
    
    # Index the merged VCF file
    index_vcf_file(merged_vcf, bcftools_path)
    
    # Normalize and split multi-allelic variants in the merged VCF file
    normalized_merged_vcf = "normalized_merged_output.vcf"
    normalize_and_split_vcf(merged_vcf, normalized_merged_vcf, local_reference_genome, bcftools_path)
    compress_vcf_with_bgzip(normalized_merged_vcf, bgzip_path)
    
    # Index the normalized and compressed merged VCF file
    index_vcf_file(f"{normalized_merged_vcf}.gz", bcftools_path)
    
    # Split the merged VCF file by chromosome, preserving autosomes and X/Y when present
    split_vcf_files = split_vcf_by_chromosome(f"{normalized_merged_vcf}.gz", bcftools_path)
    if split_vcf_files is None:
        raise RuntimeError("Failed to split the merged VCF file by chromosome.")
    
    output_vcf_dxfile = dxpy.upload_local_file(merged_vcf)
    split_vcf_dxfiles = [dxpy.upload_local_file(vcf) for vcf in split_vcf_files]
    
    return {
        "merged_vcf": dxpy.dxlink(output_vcf_dxfile),
        "split_vcfs": [dxpy.dxlink(vcf) for vcf in split_vcf_dxfiles]
    }

dxpy.run()