#!/bin/bash
# favorannotator_v1.0.0
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of outfile: '$outfile'"
    echo "Value of gds_file: '$gds_file'"
    echo "Value of chromosome: '$chromosome'"
    echo "Value of use_compression: '$use_compression'"
    echo "Value of favor_csv_database: '$favor_csv_database'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

      # Download GDS file if provided
    if [ -n "$gds_file" ]; then
        dx download "$gds_file" -o gds_file.gds &
        gds_file2="gds_file.gds"
    else
        gds_file2="NO_GDS_FILE"
    fi

    # Download favor_csv_database if provided
    if [ -n "$favor_csv_database" ]; then
        dx download "$favor_csv_database" -o favor_csv_database.txt &
        favor_csv_database2="favor_csv_database.txt"
    else
        favor_csv_database2="NO_TXT_FILE"
    fi

    # Install Rust and xsv on the host system
    echo "Installing Rust and xsv"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y

    # Ensure the correct path is sourced for Rust
    echo 'source $HOME/.cargo/env' >> ~/.bashrc
	source $HOME/.cargo/env
	rustc --version


    # Install xsv using Cargo
    cargo install xsv
	xsv --version


	# Run the R script inside the Docker container and mount xsv from the host
    echo "Running R script with xsv inside the Docker container"
    dx-docker run -v /home/dnanexus/:/home/dnanexus/ \
                  -v /home/dnanexus/.cargo/bin:/home/dnanexus/.cargo/bin \
                  -e PATH="/home/dnanexus/.cargo/bin:$PATH" \
                  -w /home/dnanexus/ \
                  zilinli/staarpipeline:0.9.7 \
                  Rscript --vanilla favorannotator.R $outfile $gds_file2 $chromosome $use_compression $favor_csv_database2

    # Move and upload the result
    mkdir -p out/results
    mv ${outfile}.gds out/results
    dx-upload-all-outputs
}